import type { Config } from 'tailwindcss';
import {
  iconsPlugin,
  getIconCollections,
} from '@egoist/tailwindcss-icons';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,ts,js}'],
  theme: {
    extend: {
      colors: {
        n: {
          slate: {
            1: 'rgb(var(--slate-1) / <alpha-value>)',
            2: 'rgb(var(--slate-2) / <alpha-value>)',
            3: 'rgb(var(--slate-3) / <alpha-value>)',
            4: 'rgb(var(--slate-4) / <alpha-value>)',
            5: 'rgb(var(--slate-5) / <alpha-value>)',
            6: 'rgb(var(--slate-6) / <alpha-value>)',
            7: 'rgb(var(--slate-7) / <alpha-value>)',
            8: 'rgb(var(--slate-8) / <alpha-value>)',
            9: 'rgb(var(--slate-9) / <alpha-value>)',
            10: 'rgb(var(--slate-10) / <alpha-value>)',
            11: 'rgb(var(--slate-11) / <alpha-value>)',
            12: 'rgb(var(--slate-12) / <alpha-value>)',
          },
          iris: {
            1: 'rgb(var(--iris-1) / <alpha-value>)',
            2: 'rgb(var(--iris-2) / <alpha-value>)',
            3: 'rgb(var(--iris-3) / <alpha-value>)',
            4: 'rgb(var(--iris-4) / <alpha-value>)',
            5: 'rgb(var(--iris-5) / <alpha-value>)',
            6: 'rgb(var(--iris-6) / <alpha-value>)',
            7: 'rgb(var(--iris-7) / <alpha-value>)',
            8: 'rgb(var(--iris-8) / <alpha-value>)',
            9: 'rgb(var(--iris-9) / <alpha-value>)',
            10: 'rgb(var(--iris-10) / <alpha-value>)',
            11: 'rgb(var(--iris-11) / <alpha-value>)',
            12: 'rgb(var(--iris-12) / <alpha-value>)',
          },
          blue: {
            1: 'rgb(var(--blue-1) / <alpha-value>)',
            2: 'rgb(var(--blue-2) / <alpha-value>)',
            3: 'rgb(var(--blue-3) / <alpha-value>)',
            4: 'rgb(var(--blue-4) / <alpha-value>)',
            5: 'rgb(var(--blue-5) / <alpha-value>)',
            6: 'rgb(var(--blue-6) / <alpha-value>)',
            7: 'rgb(var(--blue-7) / <alpha-value>)',
            8: 'rgb(var(--blue-8) / <alpha-value>)',
            9: 'rgb(var(--blue-9) / <alpha-value>)',
            10: 'rgb(var(--blue-10) / <alpha-value>)',
            11: 'rgb(var(--blue-11) / <alpha-value>)',
            12: 'rgb(var(--blue-12) / <alpha-value>)',
          },
          ruby: {
            1: 'rgb(var(--ruby-1) / <alpha-value>)',
            2: 'rgb(var(--ruby-2) / <alpha-value>)',
            3: 'rgb(var(--ruby-3) / <alpha-value>)',
            4: 'rgb(var(--ruby-4) / <alpha-value>)',
            5: 'rgb(var(--ruby-5) / <alpha-value>)',
            6: 'rgb(var(--ruby-6) / <alpha-value>)',
            7: 'rgb(var(--ruby-7) / <alpha-value>)',
            8: 'rgb(var(--ruby-8) / <alpha-value>)',
            9: 'rgb(var(--ruby-9) / <alpha-value>)',
            10: 'rgb(var(--ruby-10) / <alpha-value>)',
            11: 'rgb(var(--ruby-11) / <alpha-value>)',
            12: 'rgb(var(--ruby-12) / <alpha-value>)',
          },
          amber: {
            1: 'rgb(var(--amber-1) / <alpha-value>)',
            2: 'rgb(var(--amber-2) / <alpha-value>)',
            3: 'rgb(var(--amber-3) / <alpha-value>)',
            4: 'rgb(var(--amber-4) / <alpha-value>)',
            5: 'rgb(var(--amber-5) / <alpha-value>)',
            6: 'rgb(var(--amber-6) / <alpha-value>)',
            7: 'rgb(var(--amber-7) / <alpha-value>)',
            8: 'rgb(var(--amber-8) / <alpha-value>)',
            9: 'rgb(var(--amber-9) / <alpha-value>)',
            10: 'rgb(var(--amber-10) / <alpha-value>)',
            11: 'rgb(var(--amber-11) / <alpha-value>)',
            12: 'rgb(var(--amber-12) / <alpha-value>)',
          },
          teal: {
            1: 'rgb(var(--teal-1) / <alpha-value>)',
            2: 'rgb(var(--teal-2) / <alpha-value>)',
            3: 'rgb(var(--teal-3) / <alpha-value>)',
            4: 'rgb(var(--teal-4) / <alpha-value>)',
            5: 'rgb(var(--teal-5) / <alpha-value>)',
            6: 'rgb(var(--teal-6) / <alpha-value>)',
            7: 'rgb(var(--teal-7) / <alpha-value>)',
            8: 'rgb(var(--teal-8) / <alpha-value>)',
            9: 'rgb(var(--teal-9) / <alpha-value>)',
            10: 'rgb(var(--teal-10) / <alpha-value>)',
            11: 'rgb(var(--teal-11) / <alpha-value>)',
            12: 'rgb(var(--teal-12) / <alpha-value>)',
          },
          gray: {
            1: 'rgb(var(--gray-1) / <alpha-value>)',
            2: 'rgb(var(--gray-2) / <alpha-value>)',
            3: 'rgb(var(--gray-3) / <alpha-value>)',
            4: 'rgb(var(--gray-4) / <alpha-value>)',
            5: 'rgb(var(--gray-5) / <alpha-value>)',
            6: 'rgb(var(--gray-6) / <alpha-value>)',
            7: 'rgb(var(--gray-7) / <alpha-value>)',
            8: 'rgb(var(--gray-8) / <alpha-value>)',
            9: 'rgb(var(--gray-9) / <alpha-value>)',
            10: 'rgb(var(--gray-10) / <alpha-value>)',
            11: 'rgb(var(--gray-11) / <alpha-value>)',
            12: 'rgb(var(--gray-12) / <alpha-value>)',
          },
          violet: {
            1: 'rgb(var(--violet-1) / <alpha-value>)',
            2: 'rgb(var(--violet-2) / <alpha-value>)',
            3: 'rgb(var(--violet-3) / <alpha-value>)',
            4: 'rgb(var(--violet-4) / <alpha-value>)',
            5: 'rgb(var(--violet-5) / <alpha-value>)',
            6: 'rgb(var(--violet-6) / <alpha-value>)',
            7: 'rgb(var(--violet-7) / <alpha-value>)',
            8: 'rgb(var(--violet-8) / <alpha-value>)',
            9: 'rgb(var(--violet-9) / <alpha-value>)',
            10: 'rgb(var(--violet-10) / <alpha-value>)',
            11: 'rgb(var(--violet-11) / <alpha-value>)',
            12: 'rgb(var(--violet-12) / <alpha-value>)',
          },
          black: '#000000',
          brand: '#7B5EA7',
          background: 'rgb(var(--background-color) / <alpha-value>)',
          'input-background': 'rgba(var(--background-input-box))',
          surface: {
            1: 'rgb(var(--surface-1) / <alpha-value>)',
            2: 'rgb(var(--surface-2) / <alpha-value>)',
            active: 'rgb(var(--surface-active) / <alpha-value>)',
          },
          solid: {
            1: 'rgb(var(--solid-1) / <alpha-value>)',
            2: 'rgb(var(--solid-2) / <alpha-value>)',
            3: 'rgb(var(--solid-3) / <alpha-value>)',
            active: 'rgb(var(--solid-active) / <alpha-value>)',
            amber: 'rgb(var(--solid-amber) / <alpha-value>)',
            'amber-button': 'rgb(var(--solid-amber-button) / <alpha-value>)',
            blue: 'rgb(var(--solid-blue) / <alpha-value>)',
            'blue-2': 'rgb(var(--solid-blue-2) / <alpha-value>)',
            red: 'rgb(var(--solid-red) / <alpha-value>)',
            iris: 'rgb(var(--solid-iris) / <alpha-value>)',
            purple: 'rgb(var(--solid-purple) / <alpha-value>)',
          },
          alpha: {
            1: 'rgba(var(--alpha-1))',
            2: 'rgba(var(--alpha-2))',
            3: 'rgba(var(--alpha-3))',
            black1: 'rgba(var(--black-alpha-1))',
            black2: 'rgba(var(--black-alpha-2))',
            white: 'rgba(var(--white-alpha))',
          },
          weak: 'rgb(var(--border-weak) / <alpha-value>)',
          container: 'rgba(var(--border-container))',
          strong: 'rgb(var(--border-strong) / <alpha-value>)',
          'blue-strong': 'rgb(var(--border-blue-strong) / <alpha-value>)',
          'blue-border': 'rgba(var(--border-blue))',
          'blue-text': 'rgb(var(--text-blue) / <alpha-value>)',
          'purple-text': 'rgb(var(--text-purple) / <alpha-value>)',
          'amber-text': 'rgb(var(--text-amber) / <alpha-value>)',
          card: 'rgb(var(--card-color) / <alpha-value>)',
          overlay: {
            DEFAULT: 'rgba(var(--overlay))',
            avatar: 'rgba(var(--overlay-avatar))',
          },
          button: {
            color: 'rgb(var(--button-color) / <alpha-value>)',
            hover: 'rgb(var(--button-hover-color) / <alpha-value>)',
          },
          label: {
            color: 'rgb(var(--label-background) / <alpha-value>)',
            border: 'rgba(var(--label-border))',
          },
        },
      },
      fontFamily: {
        sans: ['"DM Sans"', 'Inter', 'sans-serif'],
      },
    },
  },
  plugins: [
    iconsPlugin({
      collections: getIconCollections(['lucide']),
    }),
  ],
} satisfies Config;
